### PR TITLE
Add dependencies section to README

### PR DESCRIPTION
**Pull request by hawkeyetwolf**

### CODE REVIEW

**Comment by hawkeyetwolf** [comment]
I can haz admin rights to this repo? Right now I can't add reviewers and assignees to the PR.

**Comment by soniktrooth** [comment]
NO! I need to retain ALL THE POWER

**Comment by soniktrooth** [comment]
Ok, I relent. You now haz adminz.

**Review by soniktrooth — COMMENTED** [review]
Noice

**Pull request merged**
